[package]
name = "feature-detection"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.25.9", default-features = false, features = [
    "png",
    "jpeg",
] }
nalgebra = "0.34.1"

[profile.release]
debug = true